<a href="https://colab.research.google.com/github/athirapsalin/Pytorch_DeepLearning/blob/main/Pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Starting PyTorch")

Starting PyTorch


In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [3]:
print("Resource: https://colab.research.google.com/github/mrdbourke/pytorch-deep-learning/blob/main/00_pytorch_fundamentals.ipynb")

Resource: https://colab.research.google.com/github/mrdbourke/pytorch-deep-learning/blob/main/00_pytorch_fundamentals.ipynb


In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


Introduction to Tensors

In [5]:
# Scalers
scalers = torch.tensor(7)
scalers

tensor(7)

In [6]:
##pytorch tensors are created using torch.tensor

In [8]:
scalers.ndim

0

In [10]:
#Get tensor back as int
scalers.item()

7

In [11]:
# Vector
vector = torch.tensor([1, 7])

In [12]:
vector.ndim

1

In [15]:
vector.shape

torch.Size([2])

In [16]:
len(vector)

2

In [17]:
#Matrix
matrix = torch.tensor([[7,8], [4, 6]])

In [18]:
matrix

tensor([[7, 8],
        [4, 6]])

In [19]:
matrix.ndim

2

In [20]:
matrix.shape

torch.Size([2, 2])

In [21]:
len(matrix)

2

In [29]:
##Tensor
TENSOR = torch.tensor([[[3, 5],
                          [3, 6],
                         [4, 6]]])

In [30]:
TENSOR

tensor([[[3, 5],
         [3, 6],
         [4, 6]]])

In [31]:
TENSOR.ndim

3

In [32]:
TENSOR.shape

torch.Size([1, 3, 2])

In [54]:
TENSOR[0,:,1]

tensor([5, 6, 6])

### Random Tensors

Why random tensors?
Random tensors are important beacuse the way many neural networks learn is they start with random numbers and then adjust those random numbers to better represent the data.

'Start with random numbers _. look at data-> update random numbers -> look at data -> update random numbers

In [56]:
## Create a random tensor of size (3, 4)

In [67]:
random_tensor = torch.rand(3, 4)


In [68]:
random_tensor

tensor([[0.5601, 0.1957, 0.9490, 0.4651],
        [0.9235, 0.2499, 0.1862, 0.6862],
        [0.7865, 0.7503, 0.0480, 0.5349]])

In [69]:
random_tensor.ndim

2

In [70]:
## Create  a random tensor with similar shape to image tensor

In [71]:
random_image_size_tensor = torch.rand(size= (224,224, 3)) ## height, width, color channels (R, G, B)

In [72]:
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

Zeros and Ones

In [74]:
# Create a tensor of all zeros
zero = torch.zeros(size = (3,4))

In [76]:
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [78]:
zero*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [79]:
# create a tensor of all ones
ones = torch.ones(3,4)

In [81]:
w = ones*random_tensor

In [83]:
w == random_tensor

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [84]:
ones.dtype

torch.float32

In [85]:
random_tensor.dtype

torch.float32

In [86]:
### Create a range of tensors and tensor-like

In [88]:
## Use torch.range()
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
torch.range(0,10)

<ipython-input-89-dfdec9b83f7d>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [90]:
torch.__version__

'2.0.1+cu118'